In [11]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,  association_rules

In [12]:
df = pd.read_csv('customer.csv')

In [13]:
backup_df = df

In [14]:
df.head()

CustomerID  Gender  Age  Annual Income ($)  Spending Score (1-100)  \
0           1    Male   19              15000                      39   
1           2    Male   21              35000                      81   
2           3  Female   20              86000                       6   
3           4  Female   23              59000                      77   
4           5  Female   31              38000                      40   

      Profession  Work Experience  Family Size Graduated  
0     Healthcare                1            4       Yes  
1       Engineer                3            3       Yes  
2       Engineer                1            1        No  
3         Lawyer                0            2        No  
4  Entertainment                2            6        No

In [15]:
df.drop(['Profession', 'Graduated','Gender'], axis=1, inplace=True)
df.head()

CustomerID  Age  Annual Income ($)  Spending Score (1-100)  \
0           1   19              15000                      39   
1           2   21              35000                      81   
2           3   20              86000                       6   
3           4   23              59000                      77   
4           5   31              38000                      40   

   Work Experience  Family Size  
0                1            4  
1                3            3  
2                1            1  
3                0            2  
4                2            6

In [16]:
arr = df.to_numpy()
print(arr)
arr = np.transpose(arr)
print(arr)
arr = arr[1:]
print(arr)

[[     1     19  15000     39      1      4]
 [     2     21  35000     81      3      3]
 [     3     20  86000      6      1      1]
 ...
 [  1998     87  90961     14      9      2]
 [  1999     77 182109      4      7      2]
 [  2000     90 110610     52      5      2]]
[[     1      2      3 ...   1998   1999   2000]
 [    19     21     20 ...     87     77     90]
 [ 15000  35000  86000 ...  90961 182109 110610]
 [    39     81      6 ...     14      4     52]
 [     1      3      1 ...      9      7      5]
 [     4      3      1 ...      2      2      2]]
[[    19     21     20 ...     87     77     90]
 [ 15000  35000  86000 ...  90961 182109 110610]
 [    39     81      6 ...     14      4     52]
 [     1      3      1 ...      9      7      5]
 [     4      3      1 ...      2      2      2]]


In [17]:
# Encoding
tr = TransactionEncoder()
tr_arr = tr.fit(arr).transform(arr)
df = pd.DataFrame(tr_arr, columns = tr.columns_)
df.head()

0       1       2       3       4       5       6       7       8       \
0    True    True    True    True    True    True    True    True    True   
1    True   False   False   False   False   False   False   False   False   
2    True    True    True    True    True    True    True    True    True   
3    True    True    True    True    True    True    True    True    True   
4   False    True    True    True    True    True    True    True    True   

   9       ...  189369  189446  189498  189630  189650  189672  189689  \
0    True  ...   False   False   False   False   False   False   False   
1   False  ...    True    True    True    True    True    True    True   
2    True  ...   False   False   False   False   False   False   False   
3    True  ...   False   False   False   False   False   False   False   
4    True  ...   False   False   False   False   False   False   False   

   189709  189945  189974  
0   False   False   False  
1    True    True    True  
2   False   False   False  
3   False   False   False  
4   False   False   False  

[5 rows x 1886 columns]

In [18]:
#Applying Apriori
from mlxtend.frequent_patterns import apriori
frequent_itemsets = apriori(df, min_support = 0.5, use_colnames = True) 
frequent_itemsets.head()

support itemsets
0      0.8      (0)
1      0.8      (1)
2      0.8      (2)
3      0.8      (3)
4      0.8      (4)